export interface TimezoneGroup {
  group: string;
  options: { value: string; label: string }[];
}

export const TIMEZONE_GROUPS: TimezoneGroup[] = [
  {
    group: "Brasil",
    options: [
      { value: "America/Sao_Paulo", label: "Brasília / São Paulo (GMT-3)" },
      { value: "America/Manaus", label: "Manaus (GMT-4)" },
      { value: "America/Belem", label: "Belém (GMT-3)" },
      { value: "America/Fortaleza", label: "Fortaleza (GMT-3)" },
      { value: "America/Recife", label: "Recife (GMT-3)" },
      { value: "America/Bahia", label: "Salvador (GMT-3)" },
      { value: "America/Cuiaba", label: "Cuiabá (GMT-4)" },
      { value: "America/Campo_Grande", label: "Campo Grande (GMT-4)" },
      { value: "America/Porto_Velho", label: "Porto Velho (GMT-4)" },
      { value: "America/Boa_Vista", label: "Boa Vista (GMT-4)" },
      { value: "America/Rio_Branco", label: "Rio Branco (GMT-5)" },
      { value: "America/Noronha", label: "Fernando de Noronha (GMT-2)" },
    ],
  },
  {
    group: "Américas",
    options: [
      { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires (GMT-3)" },
      { value: "America/Santiago", label: "Santiago (GMT-4)" },
      { value: "America/Bogota", label: "Bogotá (GMT-5)" },
      { value: "America/Lima", label: "Lima (GMT-5)" },
      { value: "America/Caracas", label: "Caracas (GMT-4)" },
      { value: "America/La_Paz", label: "La Paz (GMT-4)" },
      { value: "America/Asuncion", label: "Asunción (GMT-3)" },
      { value: "America/Montevideo", label: "Montevidéu (GMT-3)" },
      { value: "America/Mexico_City", label: "Cidade do México (GMT-6)" },
      { value: "America/New_York", label: "Nova York (GMT-5)" },
      { value: "America/Chicago", label: "Chicago (GMT-6)" },
      { value: "America/Denver", label: "Denver (GMT-7)" },
      { value: "America/Los_Angeles", label: "Los Angeles (GMT-8)" },
      { value: "America/Anchorage", label: "Anchorage (GMT-9)" },
      { value: "America/Toronto", label: "Toronto (GMT-5)" },
      { value: "America/Vancouver", label: "Vancouver (GMT-8)" },
      { value: "America/Havana", label: "Havana (GMT-5)" },
      { value: "Pacific/Honolulu", label: "Honolulu (GMT-10)" },
    ],
  },
  {
    group: "Europa",
    options: [
      { value: "Europe/London", label: "Londres (GMT+0)" },
      { value: "Europe/Lisbon", label: "Lisboa (GMT+0)" },
      { value: "Europe/Madrid", label: "Madri (GMT+1)" },
      { value: "Europe/Paris", label: "Paris (GMT+1)" },
      { value: "Europe/Berlin", label: "Berlim (GMT+1)" },
      { value: "Europe/Rome", label: "Roma (GMT+1)" },
      { value: "Europe/Amsterdam", label: "Amsterdã (GMT+1)" },
      { value: "Europe/Brussels", label: "Bruxelas (GMT+1)" },
      { value: "Europe/Zurich", label: "Zurique (GMT+1)" },
      { value: "Europe/Vienna", label: "Viena (GMT+1)" },
      { value: "Europe/Warsaw", label: "Varsóvia (GMT+1)" },
      { value: "Europe/Stockholm", label: "Estocolmo (GMT+1)" },
      { value: "Europe/Helsinki", label: "Helsinque (GMT+2)" },
      { value: "Europe/Athens", label: "Atenas (GMT+2)" },
      { value: "Europe/Istanbul", label: "Istambul (GMT+3)" },
      { value: "Europe/Moscow", label: "Moscou (GMT+3)" },
      { value: "Europe/Kiev", label: "Kiev (GMT+2)" },
      { value: "Europe/Dublin", label: "Dublin (GMT+0)" },
    ],
  },
  {
    group: "África",
    options: [
      { value: "Africa/Cairo", label: "Cairo (GMT+2)" },
      { value: "Africa/Johannesburg", label: "Joanesburgo (GMT+2)" },
      { value: "Africa/Lagos", label: "Lagos (GMT+1)" },
      { value: "Africa/Nairobi", label: "Nairóbi (GMT+3)" },
      { value: "Africa/Casablanca", label: "Casablanca (GMT+1)" },
      { value: "Africa/Algiers", label: "Argel (GMT+1)" },
      { value: "Africa/Luanda", label: "Luanda (GMT+1)" },
      { value: "Africa/Maputo", label: "Maputo (GMT+2)" },
    ],
  },
  {
    group: "Ásia",
    options: [
      { value: "Asia/Dubai", label: "Dubai (GMT+4)" },
      { value: "Asia/Tehran", label: "Teerã (GMT+3:30)" },
      { value: "Asia/Karachi", label: "Karachi (GMT+5)" },
      { value: "Asia/Kolkata", label: "Mumbai / Calcutá (GMT+5:30)" },
      { value: "Asia/Dhaka", label: "Daca (GMT+6)" },
      { value: "Asia/Bangkok", label: "Bangkok (GMT+7)" },
      { value: "Asia/Jakarta", label: "Jacarta (GMT+7)" },
      { value: "Asia/Singapore", label: "Singapura (GMT+8)" },
      { value: "Asia/Hong_Kong", label: "Hong Kong (GMT+8)" },
      { value: "Asia/Shanghai", label: "Xangai / Pequim (GMT+8)" },
      { value: "Asia/Taipei", label: "Taipé (GMT+8)" },
      { value: "Asia/Seoul", label: "Seul (GMT+9)" },
      { value: "Asia/Tokyo", label: "Tóquio (GMT+9)" },
      { value: "Asia/Manila", label: "Manila (GMT+8)" },
      { value: "Asia/Riyadh", label: "Riad (GMT+3)" },
      { value: "Asia/Jerusalem", label: "Jerusalém (GMT+2)" },
    ],
  },
  {
    group: "Oceania",
    options: [
      { value: "Australia/Sydney", label: "Sydney (GMT+10)" },
      { value: "Australia/Melbourne", label: "Melbourne (GMT+10)" },
      { value: "Australia/Brisbane", label: "Brisbane (GMT+10)" },
      { value: "Australia/Perth", label: "Perth (GMT+8)" },
      { value: "Australia/Adelaide", label: "Adelaide (GMT+9:30)" },
      { value: "Pacific/Auckland", label: "Auckland (GMT+12)" },
      { value: "Pacific/Fiji", label: "Fiji (GMT+12)" },
      { value: "Pacific/Guam", label: "Guam (GMT+10)" },
    ],
  },
  {
    group: "Atlântico",
    options: [
      { value: "Atlantic/Azores", label: "Açores (GMT-1)" },
      { value: "Atlantic/Cape_Verde", label: "Cabo Verde (GMT-1)" },
      { value: "Atlantic/Reykjavik", label: "Reykjavik (GMT+0)" },
    ],
  },
  {
    group: "UTC",
    options: [{ value: "UTC", label: "UTC (GMT+0)" }],
  },
];
